### ISSUE TITLE
Deployment question

### ISSUE THREAD

**Issue by cliren** [roybailey/research-graphql#2]
This is a great example and would like to run it and experience it. 

`mvn clean install` builds successfully, what web server do I need to deploy these services and test them locally?

**Comment by cliren** [comment]
@roybailey I had to include in each of the module and run them individually. Please let me know if there is an easy to way to run all of them at once.

```<build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
```

**Comment by sag7777** [comment]
how can i connect spring java.graphql and Rethinkdb database?

**Comment by roybailey** [comment]
@cliren Yes I ran them all individually, which suited my testing as I wanted to see how to handle cases when one of many services were down.  I was also only running them from the IDE, so thanks for the tip on the plugin which I expect allowed you to use command line `mvn spring-boot:run`

**Comment by roybailey** [comment]
@sag7777 you should be able to connect to any data source that supports Java API, which rethinkdb seems to have (`https://www.rethinkdb.com/api/java/`)
