### ISSUE TITLE
Experiences at production scale

### ISSUE THREAD

**Issue by cliren** [roybailey/research-graphql#3]
Thanks for putting this together, this is awesome and I am playing with it to learn more!

@roybailey Have you tried this at production scale and if so can you please share your experience and any roadblocks that we need to be aware of?

**Comment by roybailey** [comment]
Unfortunately we haven't been able to prioritise getting this into production so I can't provide any more experience than the spike gave me.  I can say that it felt from the spike work that it would have no major issues moving into production, though smart data fetching and caching might need careful thought and design.
